version: "3"

services:

  srv:
    container_name: mess_srv
    build: .
    env_file: 
      - .env
    environment:
      - POSTGRES_HOST=mess_db
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - ./client:/app/client
    depends_on:
      - db

  db:
    container_name: mess_db
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432

